### ISSUE TITLE
Iterative new log

### ISSUE THREAD

**Issue by celsocrivelaro** [codus/codelog#28]
Feature Suggestion: Iterative entry

When user creates a new entry by iterative option:

```
$ codelog new -i
```
by `-i` or `--iterative` option, user can fulfil the log entry by terminal options:

```
Enter change type:
1. Added
2. Changed
3. Deprecated
4. Removed
5. Fixed
6. Security
7. Deploy notes
> 1
Type change message
> This is a test message
Would you like to add a new log? (y/N)
> n
````

Change type is based on template file and the new option loops to the beginning. At the end, one log entry is generated with all messages

Iterative mode is a option in config file. If enabled, is default for any new log, '-i' option would not be required.

What do you think?

**Comment by rodrigomasaru** [comment]
Added support for interactive creation of the change files in #37
