### ISSUE TITLE
Version changelog preview

### ISSUE THREAD

**Issue by rmohashi** [codus/codelog#29]
## Description

Currently, I can only see the result of the version changelog, after running the `codelog release <x.y.z>` command. The problem here is that I want to see a preview of the generated `.md` file without deleting all the changes from `changelogs/unreleased`.

I suggest a method option to the `release` command, to generate that preview file, like `codelog release --preview <x.y.z>`.

**Comment by emilianoLeite** [comment]
Closed by #42
