### ISSUE TITLE
Automatically bump version

### ISSUE THREAD

**Issue by emilianoLeite** [codus/codelog#40]
It would be nice if `codelog` could automatically bump to the next major/minor/patch

## Expected Behavior
- Being on version `1.2.3`
- I can issue the comand `codelog release major`
  - And `codelog` automatically releases the version`2.0.0`

- I can issue the comand `codelog release minor`
  - And `codelog` automatically releases the version`1.3.0`

- I can issue the comand `codelog release patch`
  - And `codelog` automatically releases the version`1.2.4`

## Current Behavior
- Currently I have to manually check the current version and explicitly pass the next version in the command `codelog release <VERSION>`

## Possible Solution
- Infer the current version based on the latest file in the `releases/` folder

**Comment by emilianoLeite** [comment]
Yes, just an alias so I can use `codelog release major` instead of `codelog release 2.0.0`

**Comment by rmohashi** [comment]
Okay. If anyone wants to implement this feature, feel free to do it.

**Comment by Guilherme2112** [comment]
This issue is supposed to be solved at the PR #41
